format = """
[](#3c3836)\
$username\
[](bg:#504945 fg:#3c3836)\
$directory\
[](fg:#504945 bg:#665c54)\
$git_branch\
$git_status\
[](fg:#665c54 bg:#7c6f64)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#7c6f64 bg:#4a664d)\
$docker_context\
[](fg:#4a664d bg:#36533A)\
$time\
[ ](fg:#36533A)\
"""
 
# Disable the blank line at the start of the prompt
# add_newline = false
 
# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#3c3836"
style_root = "bg:#3c3836"
format = '[$user ]($style)'
 
[directory]
style = "bg:#504945"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
 
# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "
 
[c]
symbol = " "
style = "bg:#7c6f64"
format = '[ $symbol ($version) ]($style)'
 
[docker_context]
symbol = " "
style = "bg:#697731"
format = '[ $symbol $context ]($style) $path'
 
[elixir]
symbol = " "
style = "bg:#7c6f64"
format = '[ $symbol ($version) ]($style)'
 
[elm]
symbol = " "
style = "bg:#7c6f64"
format = '[ $symbol ($version) ]($style)'
 
[git_branch]
symbol = ""
style = "bg:#665c54"
format = '[ $symbol $branch ]($style)'
 
[git_status]
style = "bg:#665c54"
format = '[$all_status$ahead_behind ]($style)'
 
[golang]
symbol = " "
style = "bg:#7c6f64"
format = '[ $symbol ($version) ]($style)'
 
[haskell]
symbol = " "
style = "bg:#7c6f64"
format = '[ $symbol ($version) ]($style)'
 
[java]
symbol = " "
style = "bg:#7c6f64"
format = '[ $symbol ($version) ]($style)'
 
[julia]
symbol = " "
style = "bg:#7c6f64"
format = '[ $symbol ($version) ]($style)'
 
[nodejs]
symbol = ""
style = "bg:#7c6f64"
format = '[ $symbol ($version) ]($style)'
 
[nim]
symbol = " "
style = "bg:#7c6f64"
format = '[ $symbol ($version) ]($style)'
 
[rust]
symbol = ""
style = "bg:#7c6f64"
format = '[ $symbol ($version) ]($style)'
 
[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#36533A"
format = '[ ♥ $time ]($style)'
